updated script

diff --git a/runBenchmarks b/runBenchmarks
--- a/runBenchmarks
+++ b/runBenchmarks
@@ -14,6 +14,8 @@ gcc $curEx
 rc=$?
 if [[ $rc != 0 ]]; then echo "gcc failed to compile" $curEx; exit $rc; fi
 ./a.out < input > testOut
-diff testOut output 
+diff testOut output > diffOut
+rc=$?
+if [[ $rc != 0 ]]; then echo "diff failed" $curEx; fi
 popd
 done
